-- AlterTable
ALTER TABLE "users" ALTER COLUMN "created_time" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "created_time" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_time" SET DATA TYPE TIMESTAMP(3);
